version: '3'

services: 
  medcloud-api:
    container_name: 'medcloud-backend'
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: npm start
    ports: 
      - '3000:3000'
    volumes: 
      - ./backend/:/usr/app
    depends_on:
      - "medcloud-db"

  medcloud-db:
    container_name: 'medcloud-db'
    image: mysql:5.7
    restart: always
    volumes:
      - ./MySQL:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports: 
      - '3308:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "medcloud"